# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XWInterviewDemos' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for XWInterviewDemos

pod 'YYCache'

  target 'XWInterviewDemosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'XWInterviewDemosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
